// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.xin.msg.login;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xin_msg_login_SimpleMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xin_msg_login_SimpleMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\022\021com.xin.msg.login\"Q\n\rSimp" +
      "leMessage\022\n\n\002id\030\001 \001(\005\022\021\n\tis_simple\030\002 \001(\010" +
      "\022\014\n\004name\030\003 \001(\t\022\023\n\013sample_list\030\004 \003(\005B\002P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_xin_msg_login_SimpleMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xin_msg_login_SimpleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xin_msg_login_SimpleMessage_descriptor,
        new java.lang.String[] { "Id", "IsSimple", "Name", "SampleList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
